### ISSUE TITLE
Playbook hangs on a long running remote task during OCP 3 / 4 cluster deployment

### ISSUE THREAD

**Issue by pranavgaikwad** [redhat-cop/agnosticd#464]
**Describe the bug**
Playbooks hang on long running tasks even after the task is completed on remote host. This is observed in different tasks in both `ocp-workshop` and `ocp4-workshop` configs.  Here are some commonly observed tasks for which the playbooks hang and never proceed even after the tasks complete.

T1 : 
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/host-ocp-installer/tasks/main.yml#L71

T2 :
https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/ocp4-workshop/software.yml#L126

**To Reproduce**
Steps to reproduce the behavior, ex:
1. We used default configurations to deploy both ocp3 and ocp4 (apart from own_repo_path). 
2. For T2, I logged in to the `clientvm` and found `.openshift_install.log`. The cluster deployment was complete. I also verified that openshift installer process has exited. 

For T1, I do not have the complete logs with me right now, but I will update the issue as I get them.

**Expected behavior**
When the remote tasks completed, playbooks were expected to proceed to next tasks.  

**Verions (please complete the following information):**
 - Fedora 30
 - AAD version (`git log --pretty=oneline -2`)
48f10dd3f0d42a65b18d16dca06a767b7a7079f3 (HEAD -> development) Merge branch 'development' of github.com:redhat-cop/agnosticd into development
 - Ansible (`ansible --version`)
ansible 2.8.0
 - cloud provider CLI (aws-cli,  azure, ..)
awscli

**Additional context**
as suggested by @sborenst, I tried to run the playbooks from an EC2 instance which worked fine. however, i can consistently reproduce T2 on my work machine

as suggested by @Danil-Grigorev, I updated my `ansible.cfg` with ssh options -
```
[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=216000s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
``` 
this worked for both of us.

Opening this issue just for the record. It could be expected behavior due to connection problems. 

@jwmatthews

**Comment by jwmatthews** [comment]
@Danil-Grigorev did you have a thought of an alternative way of writing the shell command to execute openshift-ansible that would avoid this hang?  Thought you hit a similar problem and CI and reworked it using a block statement, registering the output to check.

**Comment by jwmatthews** [comment]
Below is a sample of code @Danil-Grigorev shared that might help to workaround the hangout issues when deploying from a regular laptop/workstation, i.e. not deploying from a host located in ec2.

https://github.com/fusor/mig-ci/blob/master/roles/ocp3_aws_deploy/tasks/deploy.yml#L4-L17

**Comment by Danil-Grigorev** [comment]
Thank you guys,

in my opinion the best working option is to set the [ssh_connection] section
in the ansible config file. None of the tasks by itself takes longer then
one hour, so ControlPersist=216000s should be more than enough. This
problem is related to shell tasks in general, here is a whole discussion on
this topic: https://github.com/ansible/ansible/issues/30411

The second option is a simple poll for the task completion, so even if the
latest query was lost, subsequent will have more chances to succeed.

**Comment by fridim** [comment]
IMO very long command like this, when run in ansible should be run asynchronously.

Doc:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html 

example:
```yaml
        - when: statclusterdir.stat.exists
          block:
          - name: destroy terraform resources (openshift-install destroy cluster)
            command: openshift-install destroy cluster --dir=/home/{{ ansible_user }}/{{ cluster_name }}/
            register: destroyr
            async: 1200
            poll: 30
```

**Comment by jwmatthews** [comment]
I tried changing the ansible.cfg that is in the agnosticd working directory with what's been recommended above, still seeing it hang. 

<pre>
Modified the ansible.cfg in the root directory of agnosticd

$ git diff ansible.cfg 
diff --git a/ansible.cfg b/ansible.cfg
index 37d0bf5d..b78a909d 100644
--- a/ansible.cfg
+++ b/ansible.cfg
@@ -13,3 +13,6 @@ bin_ansible_callbacks   = True
 
 [privilege_escalation]
 become                  = False
+
+[ssh_connection]
+ssh_args = -C -o ControlMaster=auto -o ControlPersist=216000s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

$ ansible --version
ansible 2.7.6
  config file = /Users/jmatthews/git/jwmatthews/agnosticd/ansible.cfg
  configured module search path = [u'/Users/jmatthews/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Nov 27 2018, 21:24:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
</pre>


More info below.


I'm running by using a script like below:

<pre>
# Generic Vars
ENVTYPE="ocp-workshop"
GUID=jmatthewsagn1

# Cloud Provider Settings
KEYNAME=mykey
REGION=us-east-1
CLOUDPROVIDER=ec2
HOSTZONEID='myhostzone'
BASESUFFIX='.mg.myexample.com'

# OCP Vars
NODE_COUNT=2
REPO_VERSION=3.11
OSRELEASE=3.11.104

ansible-playbook ansible/main.yml \
  -e "guid=${GUID}" \
  -e "env_type=${ENVTYPE}" \
  -e "own_repo_path=http://MYMIRROR/${OSRELEASE}" \
  -e "osrelease=${OSRELEASE}" \
  -e "repo_version=${REPO_VERSION}" \
  -e "cloud_provider=${CLOUDPROVIDER}" \
  -e "aws_region=${REGION}" \
  -e "HostedZoneId=${HOSTZONEID}" \
  -e "key_name=${KEYNAME}" \
  -e "subdomain_base_suffix=${BASESUFFIX}" \
  -e "node_instance_count=${NODE_COUNT}" \
  -e "software_to_deploy=openshift" \
  -e "course_name=ocp-workshop" -e "platform=aws" \
  -e "email=jmatthew@redhat.com" -e"output_dir=/tmp/agnostic_${GUID}" -e@../secret.yml -vv
</pre>




I let the script run for ~4.5 hours, it has not reported a time out, but it's been hung, I can see from /root/ansible.log on the bastion host that 'openshift-ansible' succeeded after running 20 minutes from when it was kicked off.

Looking at  bastion:/root/ansible.log
<pre>
# tail -n 30 /root/ansible.log
2019-06-22 12:27:16,471 p=18151 u=root |  TASK [openshift_cluster_autoscaler : Ensure the cluster-autoscaler is present] ***
2019-06-22 12:27:16,498 p=18151 u=root |  skipping: [master1.jmatthewsagn1.internal]
2019-06-22 12:27:16,509 p=18151 u=root |  PLAY [Cluster Auto Scaler Install Checkpoint End] ******************************
2019-06-22 12:27:16,591 p=18151 u=root |  TASK [Set Cluster Auto Scaler install 'Complete'] ******************************
2019-06-22 12:27:16,618 p=18151 u=root |  skipping: [master1.jmatthewsagn1.internal]
2019-06-22 12:27:16,621 p=18151 u=root |  PLAY RECAP *********************************************************************
2019-06-22 12:27:16,622 p=18151 u=root |  infranode1.jmatthewsagn1.internal : ok=132  changed=68   unreachable=0    failed=0   
2019-06-22 12:27:16,622 p=18151 u=root |  localhost                  : ok=12   changed=0    unreachable=0    failed=0   
2019-06-22 12:27:16,622 p=18151 u=root |  master1.jmatthewsagn1.internal : ok=1231 changed=501  unreachable=0    failed=0   
2019-06-22 12:27:16,622 p=18151 u=root |  node1.jmatthewsagn1.internal : ok=131  changed=67   unreachable=0    failed=0   
2019-06-22 12:27:16,622 p=18151 u=root |  node2.jmatthewsagn1.internal : ok=131  changed=67   unreachable=0    failed=0   
2019-06-22 12:27:16,622 p=18151 u=root |  support1.jmatthewsagn1.internal : ok=58   changed=8    unreachable=0    failed=0   
2019-06-22 12:27:16,622 p=18151 u=root |  INSTALLER STATUS ***************************************************************
2019-06-22 12:27:16,625 p=18151 u=root |  Initialization               : Complete (0:00:26)
2019-06-22 12:27:16,625 p=18151 u=root |  Health Check                 : Complete (0:00:09)
2019-06-22 12:27:16,626 p=18151 u=root |  Node Bootstrap Preparation   : Complete (0:03:30)
2019-06-22 12:27:16,626 p=18151 u=root |  etcd Install                 : Complete (0:00:47)
2019-06-22 12:27:16,626 p=18151 u=root |  NFS Install                  : Complete (0:00:11)
2019-06-22 12:27:16,626 p=18151 u=root |  Master Install               : Complete (0:05:21)
2019-06-22 12:27:16,626 p=18151 u=root |  Master Additional Install    : Complete (0:01:26)
2019-06-22 12:27:16,626 p=18151 u=root |  Node Join                    : Complete (0:00:47)
2019-06-22 12:27:16,627 p=18151 u=root |  Hosted Install               : Complete (0:01:01)
2019-06-22 12:27:16,627 p=18151 u=root |  Cluster Monitoring Operator  : Complete (0:00:44)
2019-06-22 12:27:16,627 p=18151 u=root |  Web Console Install          : Complete (0:00:23)
2019-06-22 12:27:16,627 p=18151 u=root |  Console Install              : Complete (0:00:19)
2019-06-22 12:27:16,627 p=18151 u=root |  Metrics Install              : Complete (0:02:04)
2019-06-22 12:27:16,627 p=18151 u=root |  metrics-server Install       : Complete (0:00:43)
2019-06-22 12:27:16,628 p=18151 u=root |  Logging Install              : Complete (0:03:09)
2019-06-22 12:27:16,628 p=18151 u=root |  Service Catalog Install      : Complete (0:03:29)
2019-06-22 12:27:16,628 p=18151 u=root |  OLM Install                  : Complete (0:00:34)
[root@bastion 0 ~]# 
</pre>



Below is sample output from the script of where it got hung and backtrace as i killed it

<pre>
TASK [host-ocp-installer : run openshift-ansible deploy_cluster.yml (3.9 and later)] **************************************************************************************************
task path: /Users/jmatthews/git/jwmatthews/agnosticd/ansible/roles/host-ocp-installer/tasks/main.yml:109

Saturday 22 June 2019  08:01:43 -0400 (0:00:00.037)       0:17:13.124 ********* 
^CProcess WorkerProcess-502:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
 [ERROR]: User interrupted execution

    self.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
    self._final_q
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/shell.py", line 27, in run
    result = command_action.run(task_vars=task_vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/command.py", line 24, in run
    results = merge_hash(results, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 840, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 959, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1088, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 337, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 978, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 815, in _bare_run
    events = selector.select(timeout)
  File "/usr/local/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 606, in select
    None, max_events, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 119, in _syscall_wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ansible/compat/selectors/_selectors2.py", line 632, in _wrap_control
    return self._kqueue.control(changelist, max_events, timeout)
KeyboardInterrupt

real	282m6.244s
user	8m18.113s
sys	1m59.548s
</pre>

**Comment by Danil-Grigorev** [comment]
[ansible.log](https://github.com/redhat-cop/agnosticd/files/3317553/ansible.log)
Here is a sample log from a run, that hit the issue. The bastion host logs shows that the installation was successful.

```
2019-06-23 00:37:00,959 p=19455 u=root |  TASK [openshift_cluster_autoscaler : Ensure the cluster-autoscaler is present] ***
2019-06-23 00:37:00,984 p=19455 u=root |  skipping: [master1.agnd-hang.internal]
2019-06-23 00:37:00,993 p=19455 u=root |  PLAY [Cluster Auto Scaler Install Checkpoint End] ******************************
2019-06-23 00:37:01,067 p=19455 u=root |  TASK [Set Cluster Auto Scaler install 'Complete'] ******************************
2019-06-23 00:37:01,093 p=19455 u=root |  skipping: [master1.agnd-hang.internal]
2019-06-23 00:37:01,095 p=19455 u=root |  PLAY RECAP *********************************************************************
2019-06-23 00:37:01,095 p=19455 u=root |  infranode1.agnd-hang.internal : ok=132  changed=68   unreachable=0    failed=0   
2019-06-23 00:37:01,096 p=19455 u=root |  localhost                  : ok=12   changed=0    unreachable=0    failed=0   
2019-06-23 00:37:01,096 p=19455 u=root |  master1.agnd-hang.internal : ok=1259 changed=502  unreachable=0    failed=0   
2019-06-23 00:37:01,096 p=19455 u=root |  node1.agnd-hang.internal   : ok=131  changed=67   unreachable=0    failed=0   
2019-06-23 00:37:01,096 p=19455 u=root |  node2.agnd-hang.internal   : ok=131  changed=67   unreachable=0    failed=0   
2019-06-23 00:37:01,096 p=19455 u=root |  support1.agnd-hang.internal : ok=30   changed=8    unreachable=0    failed=0   
2019-06-23 00:37:01,096 p=19455 u=root |  INSTALLER STATUS ***************************************************************
2019-06-23 00:37:01,099 p=19455 u=root |  Initialization               : Complete (0:00:22)
2019-06-23 00:37:01,099 p=19455 u=root |  Health Check                 : Complete (0:01:34)
2019-06-23 00:37:01,099 p=19455 u=root |  Node Bootstrap Preparation   : Complete (0:32:10)
2019-06-23 00:37:01,099 p=19455 u=root |  etcd Install                 : Complete (0:01:23)
2019-06-23 00:37:01,100 p=19455 u=root |  NFS Install                  : Complete (0:00:31)
2019-06-23 00:37:01,100 p=19455 u=root |  Master Install               : Complete (0:06:50)
2019-06-23 00:37:01,100 p=19455 u=root |  Master Additional Install    : Complete (0:14:19)
2019-06-23 00:37:01,100 p=19455 u=root |  Node Join                    : Complete (0:00:29)
2019-06-23 00:37:01,100 p=19455 u=root |  Hosted Install               : Complete (0:00:55)
2019-06-23 00:37:01,100 p=19455 u=root |  Cluster Monitoring Operator  : Complete (0:00:42)
2019-06-23 00:37:01,101 p=19455 u=root |  Web Console Install          : Complete (0:00:21)
2019-06-23 00:37:01,101 p=19455 u=root |  Console Install              : Complete (0:00:25)
2019-06-23 00:37:01,101 p=19455 u=root |  Metrics Install              : Complete (0:01:55)
2019-06-23 00:37:01,101 p=19455 u=root |  metrics-server Install       : Complete (0:00:41)
2019-06-23 00:37:01,101 p=19455 u=root |  Logging Install              : Complete (0:02:58)
2019-06-23 00:37:01,101 p=19455 u=root |  Service Catalog Install      : Complete (0:03:25)
2019-06-23 00:37:01,102 p=19455 u=root |  OLM Install                  : Complete (0:00:33)
```

Task was run with similar parameters as https://github.com/redhat-cop/agnosticd/issues/464#issuecomment-504680503
```
ansible-playbook ./ansible/main.yml \
-e "guid=${GUID}" \
-e "env_type=${ENVTYPE}" \
-e "osrelease=${OSRELEASE}" \
-e "repo_method=rhn" \
-e "update_packages=false" \
-e "rhn_pool_id_string='Employee SKU'" \
-e "repo_version=${REPO_VERSION}" \
-e "cloud_provider=${CLOUDPROVIDER}" \
-e "aws_region=${REGION}" \
-e "HostedZoneId=${HOSTZONEID}" \
-e "key_name=${KEYNAME}" \
-e "subdomain_base_suffix=${BASESUFFIX}" \
-e "node_instance_count=${NODE_COUNT}" \
-e "software_to_deploy=openshift" \
-e "email=${EMAIL}" \
-e "output_dir=${WORKSPACE}" \
-e "aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
-e "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
-e "redhat_registry_user=${SUB_USER}" \
-e "redhat_registry_password=${SUB_PASS}" \
-e "rhel_subscription_user=${SUB_USER}" \
-e "rhel_subscription_pass=${SUB_PASS}" \
-e "course_name=ocp-workshop" \
-e "platform=aws"
```
